version: '3'
services:

  micro:
    build: .
    image: micro
    command: bash -c "sleep 5; ./node_modules/.bin/nodemon src/index.js"
    environment:
      HOSTNAME: "localhost"
      HOST: 0.0.0.0
      PORT: 8080
      NODE_ENV: development
      MONGODB_URI: "mongodb://db:27017/local"
      ORIGIN: "*"
      JWTSECRET: "changethissecret"
    volumes:
      - ./src:/usr/src/app/src
      - ./test:/usr/src/app/test
      - ./config:/usr/src/app/config
    expose:
      - 8080
    networks:
      - all
    depends_on:
      - db
    ports:
      - "8080:8080"


  db:
    image: mongo:3
    command: mongod --smallfiles --quiet
    expose:
      - "27017"
    networks:
      - all

networks:
  all: